### ISSUE TITLE
set_wwr() for individual surfaces

### ISSUE THREAD

**Issue by fkfertigprof** [jamiebull1/geomeppy#100]
It is often necessary to apply different window to wall ratios for different blocks (e.g. ground floor with fully glazed retail, whereas first and above are punched windows for resi), zones (especially in multi-level mixed-use), or even individual surfaces.

To my understanding, the current code only supports applying set_wwr() to the entire building, with or without orientational mapping.

Ideally it would be possible to set the window to wall ratio(s) for individual surfaces (or lists of surfaces). This would allow a surfaces (or list thereof) to be selected for whatever criteria may be applicable to the individual project (or workflow).

_Background information; I tend to take highly detailed models (created with other tools) and modify these to obtain reference models for regulatory compliance modelling. As part of this process I typically remove all actuals windows and shading components, and apply % based glazing per block._

Kind regards,
Franz

**Comment by jamiebull1** [comment]
So I see two functions here that would be useful:

- % glazing by block
- % glazing by surface

I'll have a think about this but should be possible.

**Comment by jamiebull1** [comment]
@fkfertigprof I've added a `surfaces` parameter which accepts an iterable of surfaces. Does this suit your use case?

And sorry for the long delay. I've not been working on this project for a while, but I'm going to be back on top of it again now.

**Comment by atahosseini** [comment]
Hi Jamie
I got the same problem with surface set_wwr. Have you added the surfaces to idf.set_wwr()? Is the surfaces a list of the wall surfaces whose the windows are attached or a list of windows? I'm a bit confused, could you please put an example here?
