### ISSUE TITLE
Distortion when viewing sketchup-generated idf file from python-geoeppy

### ISSUE THREAD

**Issue by zhengzhuang3** [jamiebull1/geomeppy#150]
When I used sketchup to generate idf file and try to load and view it from gemoeppy of python, I found the geometry was totally distorted and different from the original one in Sketchup.
Anyone met this problem before and how to address it? Thank you.

**Comment by jamiebull1** [comment]
@zhengzhuang3 geomeppy was originally designed for creating geometry. Geometry import is experimental for now and still under development. When I get more time, I'll try and iron out the bugs, but for now it's not ready for real-world use.

However if you could share the files you're having problems with, that might help me identify the source of the issues.

**Comment by zhengzhuang3** [comment]
@jamiebull1  Sure. The attached files include one .osm file generated by sketchup openstudio plug-in and one idf file for energyplus. 
[Files.zip](https://github.com/jamiebull1/geomeppy/files/2474970/Files.zip)
The geometry  before importing looks like this：
![image](https://user-images.githubusercontent.com/32953951/46899976-a6fcc100-cecd-11e8-9c55-0c2531635a56.png)
after importing, the geometry totally distorted. 
![image](https://user-images.githubusercontent.com/32953951/46900004-e5927b80-cecd-11e8-9b91-b7b3f0ece95e.png)

**Comment by jamiebull1** [comment]
First, I can't open that zip file - it says it's empty when I try. Could you upload the .idf and .osm (with .txt extensions as you did before).

Second, I think this may to do with how the plugin generates geometry in order to create a more efficient IDF. I'm not sure though so I've opened a [question on Unmet Hours](https://unmethours.com/question/34901/why-is-this-idf-geometry-generated-from-sketchup-plugin/).

**Comment by zhengzhuang3** [comment]
@jamiebull1  The files have been uploaded with txt extensions including three osm files and their corresponding idf files and sketchup and gemoeppy views. 
[IDFone_building_single_story.txt](https://github.com/jamiebull1/geomeppy/files/2477161/IDFone_building_single_story.txt)
[OSMone_building_single_stroy.txt](https://github.com/jamiebull1/geomeppy/files/2477162/OSMone_building_single_stroy.txt)
[IDFtwo_buildings_multiple_story.txt](https://github.com/jamiebull1/geomeppy/files/2477163/IDFtwo_buildings_multiple_story.txt)
[OSMtwo_building_multiple_story.txt](https://github.com/jamiebull1/geomeppy/files/2477164/OSMtwo_building_multiple_story.txt)
For first "one_building_single_block", it has no problem. But it is wrong for second "two_building_multiple_block". 
  I think the plugin generates idf files in a different way than we look in sketchup. We may observe two blocks in sketchup view but when generating idf files the absolute coordinates are the same for both blocks except their zone name. I show this by following example.
[OSMtwo_building_single_story.txt](https://github.com/jamiebull1/geomeppy/files/2477149/OSMtwo_building_single_story.txt)
[IDFtwo_building_single_story.txt](https://github.com/jamiebull1/geomeppy/files/2477150/IDFtwo_building_single_story.txt)
We observe this model in sketchup like this;
![image](https://user-images.githubusercontent.com/32953951/46925714-ebb86180-d05f-11e8-96aa-7cac56fca8ea.png)
But in idf file, the coordinates for two blocks are totally same which is not reasonable. It looks like this in gemoeppy;  Yes, the two blocks are overlapped together.
![image](https://user-images.githubusercontent.com/32953951/46925747-2621fe80-d060-11e8-805c-c1776e7a820f.png)
The following is the floor coordinates of two buildings. It's observed that the coordinates are totally the same. Therefore, i think it is the problem of the plugin not gemeppy. 
![image](https://user-images.githubusercontent.com/32953951/46925970-54eca480-d061-11e8-9461-600e127a111f.png)

**Comment by lymereJ** [comment]
I could be missing something obvious ... The floor coordinates are the same but the zone origin is different: 

- `Thermal Zone: Space 101` has a `X Origin` of 6
- `Thermal Zone: Space 101` has a `X Origin` of 16.25

It seems normal to me that if `GlobalGeometryRules`' `Coordinate System` is set to `Relative` to not have the two blocks overlapping with each other.

**Comment by jamiebull1** [comment]
@lymereJ I think you're right. I remember seeing this before once and planning to make sure we respected relative coords, but it fell off my radar. I'll look into it when I get a chance, unless you fancy having a crack at it?

**Comment by jamiebull1** [comment]
Perfect timing. I should have some spare time from Thursday to Sunday as well

**Comment by lymereJ** [comment]
@jamiebull1, sorry for not getting back to you last week! It's been hectic but I have something in the works. I'll be posting - hopefully - soon after I've done some testing.
