### ISSUE TITLE
The default install of Shapely points to version 1.7

### ISSUE THREAD

**Issue by yiyuan1840** [jamiebull1/geomeppy#156]
Tested both pip install and the setup.py to install the geomeppy package. It seems like shapely 1.7 is installed rather than version 1.6.4.post2 as noted in requirements.txt. 
This causes some error while importing geomeppy in python3.

**Comment by jamiebull1** [comment]
@yiyuan1840 I've been neglecting this project for a while, but don't seem to be able to reproduce this error. Is it still an issue for you when running `pip install geomeppy`?
