### ISSUE TITLE
CalledProcessError for idf.run() in tutorial

### ISSUE THREAD

**Issue by myndtrust** [jamiebull1/geomeppy#159]
What isn the run() function trying to do? I am doing the tutorial with out deviation, and am seeing the error. 
My environment is Ubuntu 18.04, Python 3.7, issues is persistent with E+V8.8 and E+V9.0.

**Comment by jamiebull1** [comment]
ìdf.run()` should run a simulation. Does idf.run() work if you use it directly from `eppy`, or only from `geomeppy`?

Can you show the traceback? Might give us some more clues

**Comment by myndtrust** [comment]
I am successful with idf.run() with from `eppy.modeleditor import IDF`, but error out when executing it with `from geomeppy import IDF`

Here is the traceback:
```
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-18-031bf0ca3325> in <module>()
----> 1 idf.run()

~/anaconda3/lib/python3.7/site-packages/eppy/modeleditor.py in run(self, **kwargs)
   1012         epw = kwargs.pop('weather', self.epw)
   1013         # run EnergyPlus
-> 1014         run(self, weather=epw, idd=idd, **kwargs)
   1015         # remove in.idf
   1016         os.remove('in.idf')

~/anaconda3/lib/python3.7/site-packages/eppy/runner/run_functions.py in run(idf, weather, output_directory, annual, design_day, idd, epmacro, expandobjects, readvars, output_prefix, output_suffix, version, verbose, ep_version)
    314     try:
    315         if verbose == 'v':
--> 316             check_call(cmd)
    317         elif verbose == 'q':
    318             check_call(cmd, stdout=open(os.devnull, 'w'))

~/anaconda3/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    339         if cmd is None:
    340             cmd = popenargs[0]
--> 341         raise CalledProcessError(retcode, cmd)
    342     return 0
    343 

CalledProcessError: Command '['/usr/local/EnergyPlus-9-0-1/energyplus', '--weather', '/home/eric/energy_plus_tutorial/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw', '--output-directory', '/home/eric/energy_plus_tutorial', '--idd', '/usr/local/EnergyPlus-9-0-1/PreProcess/IDFVersionUpdater/V9-0-0-Energy+.idd', '/home/eric/energy_plus_tutorial/in.idf']' returned non-zero exit status 1.
```

**Comment by jamiebull1** [comment]
Ok, thanks. So do any of these paths from the command listed in the called process error not exist?

    '/usr/local/EnergyPlus-9-0-1/energyplus'
    '/home/eric/energy_plus_tutorial/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw'
    '/home/eric/energy_plus_tutorial'
    '/usr/local/EnergyPlus-9-0-1/PreProcess/IDFVersionUpdater/V9-0-0-Energy+.idd'
    '/home/eric/energy_plus_tutorial/in.idf'

**Comment by myndtrust** [comment]
Theses paths all exist. I am running in Jupyteer Notebook. Could that be the issues?

**Comment by myndtrust** [comment]
I tried this in PyCharm IDE. Again using Python 3.7, in Virtual Environment.

Code Snippit:
`#from eppy import modeleditor
#from eppy.modeleditor import IDF
from geomeppy import IDF

idd = '/usr/local/EnergyPlus-9-0-1/PreProcess/IDFVersionUpdater/V9-0-0-Energy+.idd'
fname = '/usr/local/EnergyPlus-9-0-1/ExampleFiles/Minimal.idf'

IDF.setiddname(idd)
idf = IDF(fname)

idf.epw = 'USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw'

idf.add_block(
    name='Boring hut',
    coordinates=[(10,0),(10,10),(0,10),(0,0)],
    height=3.5)

idf.set_default_constructions()

idf.intersect_match()

idf.set_wwr(0.6)

idf.to_obj('boring_hut.obj')

idf.run()`

Output:
`/home/eric/energy_plus_tutorial/venv/ml/bin/python /home/eric/energy_plus_tutorial/geom_idf.py
EnergyPlus Starting
EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.03.20 06:00
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Program terminated: EnergyPlus Terminated--Error(s) Detected.
Traceback (most recent call last):
  File "/home/eric/energy_plus_tutorial/geom_idf.py", line 26, in <module>
    idf.run()
  File "/home/eric/energy_plus_tutorial/venv/ml/lib/python3.7/site-packages/eppy/modeleditor.py", line 1014, in run
    run(self, weather=epw, idd=idd, **kwargs)
  File "/home/eric/energy_plus_tutorial/venv/ml/lib/python3.7/site-packages/eppy/runner/run_functions.py", line 316, in run
    check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/EnergyPlus-9-0-1/energyplus', '--weather', '/home/eric/energy_plus_tutorial/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw', '--output-directory', '/home/eric/energy_plus_tutorial', '--idd', '/usr/local/EnergyPlus-9-0-1/PreProcess/IDFVersionUpdater/V9-0-0-Energy+.idd', '/home/eric/energy_plus_tutorial/in.idf']' returned non-zero exit status 1.

Process finished with exit code 1`

**Comment by jamiebull1** [comment]
Ah, in that case is there a .err file generated?

**Comment by myndtrust** [comment]
Here is the output of the erros file, looks like the its the Window construction that is causing the problem.

`Program Version,EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.03.20 20:24,
   ** Warning ** Weather file location will be used rather than entered (IDF) Location object.
   **   ~~~   ** ..Location object=DENVER_STAPLETON_CO_USA_WMO_724690
   **   ~~~   ** ..Weather File Location=Denver Centennial  Golden   Nr CO USA TMY3 WMO#=724666
   **   ~~~   ** ..due to location differences, Latitude difference=[3.00E-002] degrees, Longitude difference=[0.31] degrees.
   **   ~~~   ** ..Time Zone difference=[0.0] hour(s), Elevation difference=[13.53] percent, [218.00] meters.
   ** Warning ** GetHTSurfaceData: Surfaces with interface to Ground found but no "Ground Temperatures" were input.
   **   ~~~   ** Found first in surface=BLOCK BORING HUT STOREY 0 FLOOR 0001
   **   ~~~   ** Defaults, constant throughout the year of (18.0) will be used.
   ** Severe  ** FenestrationSurface:Detailed="BLOCK BORING HUT STOREY 0 WALL 0001 WINDOW", invalid Construction Name="NONE".
   ** Severe  ** FenestrationSurface:Detailed="BLOCK BORING HUT STOREY 0 WALL 0002 WINDOW", invalid Construction Name="NONE".
   ** Severe  ** FenestrationSurface:Detailed="BLOCK BORING HUT STOREY 0 WALL 0003 WINDOW", invalid Construction Name="NONE".
   ** Severe  ** FenestrationSurface:Detailed="BLOCK BORING HUT STOREY 0 WALL 0004 WINDOW", invalid Construction Name="NONE".
   **  Fatal  ** GetSurfaceData: Errors discovered, program terminates.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=4
   ..... Last severe error=FenestrationSurface:Detailed="BLOCK BORING HUT STOREY 0 WALL 0004 WINDOW", invalid Construction Name="NONE".
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 2 Warning; 4 Severe Errors; Elapsed Time=00hr 00min  0.11sec`

**Comment by myndtrust** [comment]
The construction in missing in 'set_wwr()' , but i can figure out where the constructions are defined.

```
   def set_wwr(
        self, wwr=0.2, construction=None, force=False, wwr_map={}, orientation=None
    ):
        # type: (Optional[float], Optional[str], Optional[bool], Optional[dict], Optional[str]) -> None
        """Add strip windows to all external walls.

        Different WWR can be applied to specific wall orientations using the `wwr_map` keyword arg.
        This map is a dict of wwr values, keyed by `wall.azimuth`, which overrides the default passed as `wwr`.

        They can also be applied to walls oriented to a compass point, e.g. north, which will apply to walls which
        have an azimuth within 45 degrees of due north.

        :param wwr: Window to wall ratio in the range 0.0 to 1.0.
        :param construction: Name of a window construction.
        :param force: True to remove all subsurfaces before setting the WWR.
        :param wwr_map: Mapping from wall orientation (azimuth) to WWR, e.g. {180: 0.25, 90: 0.2}.
        :param orientation: One of "north", "east", "south", "west". Walls within 45 degrees will be affected.

        """
        set_wwr(self, wwr, construction, force, wwr_map, orientation)
```

**Comment by jamiebull1** [comment]
@myndtrust The latest dev branch has the fix, but I've not had time to put a patched release out. I'll get to it when I get a chance.

**Comment by jamiebull1** [comment]
Fixed
