### ISSUE TITLE
Installing geomeppy on Mac

### ISSUE THREAD

**Issue by cecilia626** [jamiebull1/geomeppy#161]
Hi there - sorry if this isn't the right place to post this? But I'm having troubles installing geomeppy on my computer, but I keep getting this error. Could you please help?

(base) cecilias-air:~ cecilia_rose_xoair$ pip install geomeppy
Collecting geomeppy
  Using cached https://files.pythonhosted.org/packages/99/2c/f62204651a6079b1dca1ff3fb276e39045fba6d90b8f7edab8ea1a8f1ce6/geomeppy-0.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g0/vbzv4n7x6yd8vzj8lt26t9y80000gp/T/pip-install-bxr_jph_/geomeppy/setup.py", line 8, in <module>
        with open("requirements.in") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.in'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g0/vbzv4n7x6yd8vzj8lt26t9y80000gp/T/pip-install-bxr_jph_/geomeppy/
(base) cecilias-air:~ cecilia_rose_xoair$

**Comment by adambgnr** [comment]
Hi @cecilia626 
I had the same problem on Windows. Unfortunately I don't know how to fix the installation with pip, but a temporarily solution that worked for me is like this:

- Download and unpack the geomeppy-0.6.1.tar.gz file from [https://pypi.org/project/geomeppy/#files](https://pypi.org/project/geomeppy/#files)
- Download the requirements.in and test-requirements.in files from the Geomeppy GitHub repository and put them in the same folder, where the setup.py file is in the previously unpacked tar
- Open a terminal, navigate to the folder where the setup.py is and install it manually with the command: python setup.py install

**Comment by jamiebull1** [comment]
@adambgnr thanks for this. Yes, you're right. I think what I need to do is add those .in files to a manifest file, but haven't found the time for it.

**Comment by jamiebull1** [comment]
Closing, fixed in 8036e397e2e99a0caad78605feb0e7d662f7444c
