### ISSUE TITLE
Creating buildings and shading blocks from shapely outlines

### ISSUE THREAD

**Issue by jamiebull1** [jamiebull1/geomeppy#169]
Given a building outline as a shapely polygon, and a list of shading lines, how can we create a geomeppy model?

The basic function for the building blocks is `IDF.add_block(name=<building name>, coordinates=<list of (x,y) coordinates>, height=<building height>)`. You probably also want to specify `num_stories`.

For the shading surfaces, you have `IDF.add_shading_block(...)` which takes the same args as `add_block`, but you only need the coordinates and the height.

Then you'll probably want to run:

```
    idf.intersect_match()  # intersects any surfaces that adjoin other surfaces, and match to zones on the other side
    idf.set_default_constructions()  # sets all surfaces to Project Wall, Project Partition, etc.
    idf.set_wwr(0.6, construction="Project External Window")  # sets window to wall ratio on all external walls
```

Things to watch out for are blocks with complex outlines, which may have too many points. I think the limit is 120, so if you have curved walls represented as polygons with lots of small edges, they might need simplifying. Also, make sure you have any adjoining buildings added to the IDF before running `intersect_match`.

Any other questions or bugs that crop up, let me know.

**Comment by FrancisBase** [comment]
Yes this is really a breakthrough feature of Geomepppy if it can be pulled out.
Let me know how i can help please.

**Comment by jamiebull1** [comment]
I don't think anything needs to be done in geomeppy. The functions you need to use are already there. What format is the data you already have?

**Comment by FrancisBase** [comment]
The original format is SHP but i use GIS to convert it into shapely polygon(building footprint) with shapely lines (shading blocks representing contiguous buildings) surrounding.

**Comment by jamiebull1** [comment]
Ok, sounds close to what is needed for geomeppy. What exactly do you need help with?

**Comment by FrancisBase** [comment]
Need to code the transformation of the 2D figure to the 3D building in IDF retaining the properties of shading, normal facade and contiguous building (they have different thermodynamic impacts).
<a href="https://ibb.co/VJ0rV5V"><img src="https://i.ibb.co/MZyWnQn/geomeppy2.png" alt="geomeppy2" border="0"></a>

**Comment by jamiebull1** [comment]
That's what the functions I described above do. If you need someone to actually do the coding for you, let me know and I can put together a quote.

**Comment by FrancisBase** [comment]
Sent an email for us to see how we can solve this interesting code challenge ok best regards.

**Comment by jamiebull1** [comment]
Closing as handled elsewhere.
