### ISSUE TITLE
problem running geomeppy on windows

### ISSUE THREAD

**Issue by milagrossanz** [jamiebull1/geomeppy#181]
Hello! I've been working with eppy for a couple of months now and just found out about geomeppy because I'm trying to work with the function WWR. But my problem starts in the very beginning, I've tried to install geomeppy but it seems that I did something wrong and can't seem to find the error. Whenever I try to run "from geomeppy import IDF" this error show up:

from geomeppy import IDF

IDF.setiddname("C:/EnergyPlusV8-9-0/Energy+.idd")
idf = IDF("C:/EnergyPlusV8-9-0/ExampleFiles/Minimal.idf")

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-0d32bb67720b> in <module>
----> 1 from geomeppy import IDF
      2 
      3 IDF.setiddname("C:/EnergyPlusV8-9-0/Energy+.idd")
      4 idf = IDF("C:/EnergyPlusV8-9-0/ExampleFiles/Minimal.idf")

~\Anaconda3\lib\site-packages\geomeppy\__init__.py in <module>
----> 1 from geomeppy.idf import IDF
      2 
      3 __version__ = "0.11.6"
      4 
      5 __all__ = ["IDF"]

~\Anaconda3\lib\site-packages\geomeppy\idf.py in <module>
      8 from eppy.idf_msequence import Idf_MSequence  # noqa
      9 
---> 10 from .geom.intersect_match import intersect_idf_surfaces, match_idf_surfaces
     11 from .builder import Block, Zone
     12 from .geom.polygons import bounding_box, Polygon2D  # noqa

~\Anaconda3\lib\site-packages\geomeppy\geom\intersect_match.py in <module>
      3 from itertools import product
      4 
----> 5 from geomeppy.geom.surfaces import (
      6     get_adjacencies,
      7     getidfplanes,

~\Anaconda3\lib\site-packages\geomeppy\geom\surfaces.py in <module>
      8 from eppy.idf_msequence import Idf_MSequence  # noqa
      9 from numpy import float64  # noqa
---> 10 from shapely.geometry import Polygon
     11 from shapely.ops import polygonize
     12 from shapely.ops import unary_union

~\Anaconda3\lib\site-packages\shapely\geometry\__init__.py in <module>
      2 """
      3 
----> 4 from .base import CAP_STYLE, JOIN_STYLE
      5 from .geo import box, shape, asShape, mapping
      6 from .point import Point, asPoint

~\Anaconda3\lib\site-packages\shapely\geometry\base.py in <module>
     16 
     17 from shapely.affinity import affine_transform
---> 18 from shapely.coords import CoordinateSequence
     19 from shapely.errors import WKBReadingError, WKTReadingError
     20 from shapely.geos import WKBWriter, WKTWriter

~\Anaconda3\lib\site-packages\shapely\coords.py in <module>
      6 from ctypes import byref, c_double, c_uint
      7 
----> 8 from shapely.geos import lgeos
      9 from shapely.topology import Validating
     10 

~\Anaconda3\lib\site-packages\shapely\geos.py in <module>
    143     if os.getenv('CONDA_PREFIX', ''):
    144         # conda package.
--> 145         _lgeos = CDLL(os.path.join(sys.prefix, 'Library', 'bin', 'geos_c.dll'))
    146     else:
    147         try:

~\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 126] Não foi possível encontrar o módulo especificado

I'm working with JupyterLab in Anaconda, but I also checked and I have al the requirements packages installed.
I also followed what @adambgnr said on this closed issue (https://github.com/jamiebull1/geomeppy/issues/161) but it didn't work.

Thank you so much in advance to whomever finds time to help me!

**Comment by jamiebull1** [comment]
I assume you've found the solution since you've closed the issue.

In case anyone else stumbles across this problem, it looks like you need to install `shapely`. This is a common issue on Windows, and is most-easily resolved by installing in a conda environment.

**Comment by milagrossanz** [comment]
Hi @jamiebull1! I tried to install it one more time, following the steps from the tutorial very closely and this time worked. I didn't reply to my previous problem because I actually don't know how I fixed it.

I hope your message can help anyone else with this problem. Thanks!
