### ISSUE TITLE
adding blocks with internal vertices

### ISSUE THREAD

**Issue by milagrossanz** [jamiebull1/geomeppy#188]
Hello!

I was wondering if there is a way to define a block from the internal vertices and to make the surfaces of my constructions expand to the outside. 
I'm writing a code that allows me to evaluate the impact on heating demand of adding different materials and varying the thickness of the layers. By defining the building from the inside I can keep the internal volume constant.  
If I define the block with `idf.add_block ()`, the surface of this polygon will represent the outermost layer of the walls and the rest will be defined inward, right? Are there any functions I can use to define them outwards?

Thanks!!

**Comment by jamiebull1** [comment]
EnergyPlus considers the dimensions as internal dimensions. Room volumes are calculated with zero-thickness walls. "All surfaces are modeled as a thin plane (with no thickness)" ([Surfaces docs](https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-thermal-zone-description-geometry.html#surfaces)). So if you're interested in the effect of changing room volume when adding internal insulation, you can just change the coordinates of the insulated wall to the inside face of the insulation.

**Comment by milagrossanz** [comment]
thank you for your reply, @jamiebull1!
