### ISSUE TITLE
Suggestion: change WWR coordinates calculation

### ISSUE THREAD

**Issue by JoLo90** [jamiebull1/geomeppy#195]
When setting WWR to triangular surfaces, the corresponding Window extends off the edge of the surface (there is a corresponding error in the err file).

When modifying the code in the recipes.py file, the error messages disappear and the position of the windows seems more "natural" :

### Original
    window_points = [
        [
            ((x - average_x) * 0.999) + average_x,
            ((y - average_y) * 0.999) + average_y,
            ((z - average_z) * wwr) + average_z,
        ]
        for x, y, z in vertices
    ]

![OriginalGEP](https://user-images.githubusercontent.com/65318981/89433987-49410500-d743-11ea-907f-03061a7f5482.PNG)

### Modified
    wwrfact = np.sqrt(wwr) 
    window_points = [
        [
            x*wwrfact*0.999 + average_x*(1-wwrfact),
            y*wwrfact*0.999 + average_y*(1-wwrfact),
            z*wwrfact*0.999 + average_z*(1-wwrfact),
        ]
        for x, y, z in vertices
    ]

![ModifiedGEP](https://user-images.githubusercontent.com/65318981/89434450-d8e6b380-d743-11ea-99c4-a5d9b5a041c8.PNG)

I am not sure why the windows are blue-coloured in the first case and grey coloured in the second case.

Btw thanks for that great library Jamie !

**Comment by jamiebull1** [comment]
Thanks for this. Looks like a good improvement. If you'd like to open a PR I should be able to merge it in pretty quickly.
