### ISSUE TITLE
Intermediate floor\ceiling boundary conditions

### ISSUE THREAD

**Issue by xavfa** [jamiebull1/geomeppy#205]
Hi,
creating several zones per floor seem to work fine, but I found that boundary conditions for ceilings and floor were fixed to outdoor with sun and wind exposed for the ceiling and wind exposes for the floor.  The ceiling of the lower floor should be connected to the floor of the upper one. I guess this rely on the matched \ unmatched surface routine but I am not sure at all.
Please is this an error from my side or boundary condition for intermediate storey with the add_block function is missing something ?
Thanks in advance

**Comment by xavfa** [comment]
Hi,
it is something to do with the almostequal function in utilities.py
I have manage to solve this issue making a rotating routine of the polygone s.coords to check if almost equal to m.coords.
The boundary for Tutorial 3 works now as well for me.
Thanks in advance to confirm the mistakes (or to point out my mistake in using the package)

**Comment by amylee-lixinyi** [comment]
Hi,
I seems to come across the same issue of unmatched ceiling/floor as you did, could you please enlighten me how did you manage to fix this ?
Thanks.

**Comment by xavfa** [comment]
This issue could could be closed now though
