### ISSUE TITLE
idf.add_shading_block creates two surface!

### ISSUE THREAD

**Issue by orcunkoraliseri** [jamiebull1/geomeppy#35]
Actually, this does not create any problem but I thought it is better to mention about it. 'idf.add_shading_block'  method puts two similar surface in the geometry.

here it's the code that I put in the code.
`idf.add_shading_block('b_south', [[0.0, 15.0] * 2, [10.0, 15.0] * 2], 10.0)`

here it's  the outcome from idf.
`['SHADING:SITE:DETAILED', 'b_south_1', '', 'autocalculate', 0.0, 15.0, 10.0, 0.0, 15.0, 0.0, 10.0, 15.0, 0.0, 10.0, 15.0, 10.0]
`
`
['SHADING:SITE:DETAILED', 'b_south_2', '', 'autocalculate', 10.0, 15.0, 10.0, 10.0, 15.0, 0.0, 0.0, 15.0, 0.0, 0.0, 15.0, 10.0]
`

**Comment by jamiebull1** [comment]
This isn't a bug. The problem is in trying to add a shading block, not a shading surface. The coordinates passed produce a block with two walls rather than the usual three or more.

A better approach here would be to call:

    obj = idf.newidfobject("SHADING:SITE:DETAILED", "b_south")
    obj.setcoords([(0.0, 15.0, 10.0), (0.0, 15.0, 0.0), (10.0, 15.0, 0.0), (10.0, 15.0, 10.0)])
