### ISSUE TITLE
why idf.view_model() does not show shadings:zone:detailed?

### ISSUE THREAD

**Issue by orcunkoraliseri** [jamiebull1/geomeppy#6]
While implementing overhang shading for windows, i tried to check idf.view_model() as 3d visulisation but it did not show up the shading surfaces. I checked the source code of geomeppy to search the reason. It did not added in the  _get_collections  function. Is there any reason for that? 

And also could you help me to solve this issue?

**Comment by jamiebull1** [comment]
No reason, I just wasn't using them when I was writing geomeppy.  I'll take a look at adding them and anything else I've missed.

**Comment by orcunkoraliseri** [comment]
In addition to that i am currently working on parametric design for overhang shadings. I wrote it these codes to execute but as you mentioned in the source code of geoemppy it gives ,  
"The aname parameter should no longer be used.", UserWarning).

Could you offer me some another solution or clue for that?   

       # south shading design
       fenestration = idf.idfobjects['Fenestrationsurface:detailed'.upper()][0]
       s_x1 =fenestration.Vertex_1_Xcoordinate
       s_y1 =fenestration.Vertex_1_Ycoordinate
       s_z1 =fenestration.Vertex_1_Zcoordinate
       s_x4 =fenestration.Vertex_4_Xcoordinate
       s_y4 =fenestration.Vertex_4_Ycoordinate

       # remove previous shading surfaces
       for s in range(len(idf.idfobjects['SHADING:BUILDING:DETAILED'])):
       idf.removeidfobject(idf.idfobjects['SHADING:BUILDING:DETAILED'][0])

       shading_south = idf.newidfobject('SHADING:ZONE:DETAILED','shd_south_overhang',
                                Base_Surface_Name = 'zone surface south'.upper(),
                                  )
       shading_south.setcoords([(s_x1,s_y1,s_z1),(s_x1,(s_y1-1),s_z1),
                                (s_x4,(s_y4-1),s_z1),(s_x4,s_x4,s_z1)])
       print(shading_south)

**Comment by jamiebull1** [comment]
@orcunkoraliseri On the shading issue, I think I have it solved but I've run into another problem with matplotlib on mac which means I'm having trouble testing it. I've pushed the change to the `develop` branch so you can try it out if you like.

As for the warning, "The aname parameter should no longer be used." - from memory this is just my attempt to make @santoshphilip's comment in the eppy source code more visible. It shouldn't have any impact on your code as everything is backwards-compatible, so you can safely ignore the warning.

**Comment by orcunkoraliseri** [comment]
Thank you for your answer. I will try it.

**Comment by orcunkoraliseri** [comment]
It works for visualisation shading surfaces. Thank you again. On the other hand,i am currently dealing with the problem of idf.rotate() becuase it does not effect for shading surfaces. 

Should i add another getshadingsurfaces method in geom.intersect.match ?

**Comment by jamiebull1** [comment]
Sure. I haven't looked much at shading surfaces so happy to accept a pull request addressing them. Pretty much anywhere that the other surfaces are used, shading surfaces should also be included.

**Comment by jamiebull1** [comment]
Ok, rotate should be working now. I've released a new minor version which adds shading surfaces to the `translate`, `rotate` and `scale` methods.

**Comment by orcunkoraliseri** [comment]
Great work. Thank you for your effort.

**Comment by jamiebull1** [comment]
No problem. Anything else, please open up another issue.
