### ISSUE TITLE
Error: scale() got an unexpected keyword argument 'axes'

### ISSUE THREAD

**Issue by asikand-view** [jamiebull1/geomeppy#62]
idf.scale(2, axes='xy') => scale() got an unexpected keyword argument 'axes'

What is going on here? I used the method just as it was described in the documentation but it simply doesn't accept the axes parameter.

**Comment by jamiebull1** [comment]
@asikand-view `axes='xy'` is the default value for the `scale` function in `recipes.py`. You don't need it when calling the `idf.scale()` method.

**Comment by asikand-view** [comment]
I'd like to scale just one axis though? I saw this example in the documentation:

IDF.scale(2, axes='z')

But it throws the error I indicated above.

**Comment by jamiebull1** [comment]
Check out the `develop` branch. You should now be able to use `IDF.scale(2, axes='z')` to double the height of the building.

**Comment by jamiebull1** [comment]
Released now.
