### ISSUE TITLE
Modifying differently set_wwr() for each external wall 

### ISSUE THREAD

**Issue by orcunkoraliseri** [jamiebull1/geomeppy#8]
set_wwr() method impacts on all external walls with same attitude. While i check the source code of geomeppy, i saw that setcoords() method works with ggr(global geometry rules ). So i could not modify the code.

Could you offer me a solution to apply wwr  for each external walls separately?

**Comment by jamiebull1** [comment]
I've been meaning to do something about this. I'll take a look this evening.

**Comment by jamiebull1** [comment]
Ok, I've implemented something. Let me know if this works for you.

**Comment by orcunkoraliseri** [comment]
I've tried and that works great. Thank you.

**Comment by fkfertigprof** [comment]
I've run into the same issue, and can't find the work-around in the code. Could you point me in the right direction?

**Comment by fkfertigprof** [comment]
Will do, thanks
