### ISSUE TITLE
Add block to the top of the building using its corners

### ISSUE THREAD

**Issue by fernped** [jamiebull1/geomeppy#99]
Dear Jamie,

Thank for your amazing work. I have been using the geomeppy for performing the changes in IDF using python script and it was a great help. I was newbie with python when I started using the package but I was able to leverage my knowledge and change the envelope for simulation very quickly. I also saw that you had a lot of features regarding the handling of the polygon.

I would like to add a block to the top of the roofs, instead of scale the building increasing it in 30%, I would like to add the block which also creates the thermal zone for simulation. Thanks to you I am able to add the block passing "A list of (x, y) tuples representing the building outline.". I have seen that you have a lot of methods for matching the surfaces and get adjacencies within surfaces.py and polygons.py. Nevertheless I have not found an easy way to get the vertices of the top block that it could be used to add an additional block to the top.

Could you please explain me if you considered this case and if yes what would you suggest.

Thanks in advance.

**Comment by jamiebull1** [comment]
Thanks, that seems much clearer. I'm at the day job right now, but I'll have a proper look this evening.

**Comment by fernped** [comment]
Hello Jamie,

Thank you for the answer. Meanwhile I've found a workaround but I am still interested in working with you if you are interested to create a block automatically in the outline of an existing building.

My last approach was to read all the edges of the roofs and remove the duplicated vertices. My issue after is the order of the new vertices. Code below:

....

 proofs = [
                roof for roof in self.idfobjects['BuildingSurface:Detailed'.upper()]
                if (roof.Zone_Name.split(':')[0] == floor and
                    roof.Outside_Boundary_Condition.lower() == 'outdoors' and
                    roof.Surface_Type.lower() == 'roof')
            ]
            pwalls = [
                wall for wall in self.idfobjects['BuildingSurface:Detailed'.upper()]
                if wall.Zone_Name.split(':')[0] == floor and
                    wall.Outside_Boundary_Condition.lower() == 'outdoors' and
                    wall.Wind_Exposure.lower() == 'windexposed' and
                    wall.Surface_Type.lower() == 'wall'
            ]

            edges = []
            allvertices = []
            for poly in proofs:
                edges.extend(Polygon3D(poly.coords).edges)
            for point in edges:
                vertice = tuple(list(point)[0])
                if vertice not in allvertices:
                    allvertices.append(vertice)

            type_poly = is_convex_polygon(allvertices)
            print(str(type_poly).upper())

            print("%s  \t %s" % (allvertices, count))
            self.add_block("pv %i" % count, allvertices, height)

.....

**Comment by jamiebull1** [comment]
This ought to be a useful trick, using functions from `pyclipper`. I'll try to think of a good way to add this into `geomeppy`. Any suggestions and/or pull requests are welcome.
    
    from pyclipper import SimplifyPolygon, SimplifyPolygons
    # get your collection of roofs
    ...
    # merge and simplify them into outline coords (maybe split them up by z-coord or block first)
    coords = [SimplifyPolygon(p) for p in SimplifyPolygons([zip(poly.xs, poly.ys) for poly in proofs])]

**Comment by jamiebull1** [comment]
No problem, I only found this pair of functions myself yesterday while looking into a different solution. This approach will avoid your problem of vertices being out of order though.

I'm thinking of adding a function to `geomeppy` to return the outline of all blocks using this, which could be useful for visualisation of results.

The call signature would be something like:

    def perimeter(surfaces, level="ground"):
        """Returns the perimeter in x,y coordinates of a collection of surfaces.

        :param surfaces: List of surfaces.
        :param level: One of "ground" or "roof". Defaults to "ground".
        """

This also suggests to me some kind of filtering system to simplify the selection of surfaces. I'll open another issue about that, possibly even at the main `eppy` repository.

**Comment by jamiebull1** [comment]
Closing for #172
